apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: elasticsearch
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      containers:
        - image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
          name: elasticsearch
          ports:
            - name: http
              containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "true"
            - name: xpack.security.transport.ssl.enabled
              value: "true"
            - name: xpack.security.http.ssl.enabled
              value: "true"
            - name: xpack.security.http.ssl.keystore.path
              value: /usr/share/elasticsearch/config/certs/tls.crt
            - name: xpack.security.http.ssl.keystore.password
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-tls
                  key: tls.key
            - name: xpack.security.http.ssl.truststore.path
              value: /usr/share/elasticsearch/config/certs/tls.crt
            - name: xpack.security.http.ssl.truststore.password
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-tls
                  key: tls.key
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "2Gi"
              cpu: "1"
          volumeMounts:
            - name: elasticsearch-cert
              mountPath: /usr/share/elasticsearch/config/certs
              readOnly: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      volumes:
        - name: elasticsearch-cert
          secret:
            secretName: elasticsearch-tls
