# # Useful examples on how to configure Prometheus
# # * https://www.weave.works/prometheus-and-kubernetes-monitoring-your-applications/
# # * https://grafana.net/dashboards/162
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: prometheus-alertrules
#   namespace: monitoring
# data:
#   alert.rules: |-
#     groups:
#     - name: HighErrorRate
#       rules:
#       - alert: HighErrorRate
#         expr: rate(request_duration_seconds_count{status_code="500"}[5m]) > 1
#         for: 2m
#         labels:
#           severity: critical
#         annotations:
#           summary: "High HTTP 500 error rates"
#           description: "Rate of HTTP 500 errors per 5 minutes: {{ $value }}"
#     - name: test-alerts
#       rules:
#       - alert: HighCpuUsage
#         expr: sum(rate(node_cpu_seconds_total{mode!="idle"}[1m])) by (instance) > 0.01
#         for: 1m
#         labels:
#           severity: critical
#         annotations:
#           summary: "High CPU usage detected"
#           description: "CPU usage is above 50% for more than 1 minute on {{ $labels.instance }}"
#     - name: example
#       rules:
#       - alert: HighCPUUsage
#         expr: (sum(rate(container_cpu_usage_seconds_total{container!="",container!="POD"}[1m])) by (container)) > 0.01
#         for: 1m
#         labels:
#           severity: slack
#         annotations:
#           summary: "High CPU usage detected"
#           description: "CPU usage is above 1% for the last 5 minutes."

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertrules
  namespace: monitoring
data:
  alert.rules: |-
    groups:
    - name: HighErrorRate
      rules:
      - alert: HighErrorRate
        expr: rate(request_duration_seconds_count{status_code="500"}[5m]) > 1
        for: 5m
        labels:
          severity: slack
        annotations:
          summary: "High HTTP 500 error rates"
          description: "Rate of HTTP 500 errors per 5 minutes: {{ $value }}"
          
    - name: test-alerts
      rules:
      - alert: HighCpuUsage
        expr: sum(rate(node_cpu_seconds_total{mode!="idle"}[1m])) by (instance) > 0.01
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 1% for more than 1 minute on {{ $labels.instance }}"
          
    - name: example
      rules:
      - alert: HighCPUUsage
        expr: (sum(rate(container_cpu_usage_seconds_total{container!="",container!="POD"}[1m])) by (container)) > 0.01
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 1% for the last 1 minute."
