# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: alertmanager
# data:
#   config.yml: |-
#     global:
#       slack_api_url: https://hooks.slack.com/services/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

#     route:
#       group_by: [cluster]
#       # If an alert isn't caught by a route, send it slack.
#       receiver: slack-all
#       routes:
#         - match:
#             severity: slack
#           receiver: slack-all


#     receivers:
#     - name: 'slack-all'
#       slack_configs:
#       - channel: '#alerts'
#         send_resolved: true
#         title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
#         text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
#         api_url: https://hooks.slack.com/services/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
#   configure_secret.sh: |-
#     echo 'Configuring Slack hook url.'
#     sed -i -e s,API_URL_SECRET,"$SLACK_HOOK_URL",g /etc/alertmanager/config.yml
#     exec /bin/alertmanager $*

kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
data:
  config.yml: |-
    global:
      slack_api_url: https://hooks.slack.com/services/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

    route:
      group_by: [cluster]
      receiver: slack-all
      routes:
        - match:
            severity: slack
          receiver: slack-all
        - match:
            severity: critical
          receiver: slack-critical

    receivers:
    - name: 'slack-all'
      slack_configs:
      - channel: '#alerts'
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        api_url: https://hooks.slack.com/services/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

    - name: 'slack-critical'
      slack_configs:
      - channel: '#alerts'
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        api_url: https://hooks.slack.com/services/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


