# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: socks-shop-tls
#   namespace: sock-shop
# spec:
#   secretName: socks-shop-tls
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   commonName: www.dev26x.com.ng
#   dnsNames:
#   - www.dev26x.com.ng

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: socks-shop-tls
  namespace: sock-shop
spec:
  secretName: socks-shop-tls
  dnsNames:
  - www.dev26x.com.ng
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  usages:
  - digital signature
  - key encipherment
  - server auth
