name: Setup Alerting

on:
  workflow_run:
    workflows: ["Deploy Grafana"]
    types:
      - completed

jobs:
  alerting:
    name: Setup Alerting
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Alerting Setup Script
        run: |
          chmod +x scripts/alerting.sh
          scripts/alerting.sh
