name: Deploy Alerting

on:
  workflow_run:
    workflows: ["Deploy Monitoring"]
    types:
      - completed

env:
  AWS_REGION: ${{ vars.REGION }}

jobs:
  alerting:
    name: 'Deploy Alerting'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name "socksShop-eks-hakeem" --region ${{ env.AWS_REGION }}

    - name: Deploy Alerting
      run: |
        chmod +x scripts/alerting.sh
        scripts/alerting.sh
