---
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Setup and Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Terraform Deployment
      run: ./scripts/terraform-deploy.sh

  kubernetes:
    name: Deploy Kubernetes Resources
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Kubernetes Deployment
      run: ./scripts/kubernetes-deploy.sh

  alerting:
    name: Deploy Alerting Stack (Alertmanager)
    runs-on: ubuntu-latest
    needs: kubernetes

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Alerting Deployment
      run: ./scripts/alerting-deploy.sh

  monitoring:
    name: Deploy Monitoring Stack (Prometheus & Grafana)
    runs-on: ubuntu-latest
    needs: alerting

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Monitoring Deployment
      run: ./scripts/monitoring-deploy.sh

  logging:
    name: Deploy Logging Stack (Elasticsearch, Filebeat, etc.)
    runs-on: ubuntu-latest
    needs: monitoring

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Logging Deployment
      run: ./scripts/logging-deploy.sh
