name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Setup and Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Specify your desired version

    - name: Debug information
      run: |
        pwd
        ls -la ./scripts
        file ./scripts/run-terraform.sh

    - name: Make script executable
      run: chmod +x ./scripts/run-terraform.sh

    - name: Run Terraform Deployment
      run: ./scripts/run-terraform.sh
      working-directory: ./scripts

  kubernetes:
    name: Deploy Kubernetes Resources
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Make script executable
      run: chmod +x ./scripts/apply-kubernetes.sh

    - name: Run Kubernetes Deployment
      run: ./scripts/apply-kubernetes.sh
      working-directory: ./scripts

  alerting:
    name: Deploy Alerting Stack (Alertmanager)
    runs-on: ubuntu-latest
    needs: kubernetes

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Make script executable
      run: chmod +x ./scripts/alerting.sh

    - name: Run Alerting Deployment
      run: ./scripts/alerting.sh
      working-directory: ./scripts

  monitoring:
    name: Deploy Monitoring Stack (Prometheus & Grafana)
    runs-on: ubuntu-latest
    needs: alerting
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Make Prometheus script executable
      run: chmod +x ./scripts/deploy-prometheus.sh
    
    - name: Run Prometheus
      run: ./scripts/deploy-prometheus.sh
      working-directory: ./scripts
    
    - name: Make Grafana script executable
      run: chmod +x ./scripts/deploy-grafana.sh
    
    - name: Run Grafana
      run: ./scripts/deploy-grafana.sh
      working-directory: ./scripts

  logging:
    name: Deploy Logging Stack (Elasticsearch, Filebeat, etc.)
    runs-on: ubuntu-latest
    needs: monitoring

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Make script executable
      run: chmod +x ./scripts/logging.sh

    - name: Run Logging Deployment
      run: ./scripts/logging.sh
      working-directory: ./scripts