---
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Setup and Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Terraform Deployment
      run: ../../scripts/run-terraform.sh

  kubernetes:
    name: Deploy Kubernetes Resources
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Kubernetes Deployment
      run: ../../scripts/apply-kubernetes.sh

  monitoring:
    name: Deploy Monitoring Stack (Prometheus & Grafana)
    runs-on: ubuntu-latest
    needs: alerting
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Run Prometheus
      run: ../../scripts/deploy-prometheus.sh
    
    - name: Run Grafana
      run: ../../scripts/deploy-grafana.sh

  alerting:
    name: Deploy Alerting Stack (Alertmanager)
    runs-on: ubuntu-latest
    needs: kubernetes

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Alerting Deployment
      run: ../../scripts/alerting.sh

  logging:
    name: Deploy Logging Stack (Elasticsearch, Filebeat, etc.)
    runs-on: ubuntu-latest
    needs: monitoring

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Logging Deployment
      run: ../../scripts/logging.sh
