name: Deploy Grafana

on:
  workflow_run:
    workflows: ["Deploy Prometheus"]
    types:
      - completed

jobs:
  grafana:
    name: Deploy Grafana
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Grafana Deployment Script
        run: |
          chmod +x scripts/deploy_grafana.sh
          scripts/deploy_grafana.sh
