name: Deploy Grafana

on:
  workflow_run:
    workflows: ["Deploy Prometheus"]
    types:
      - completed

jobs:
  grafana:
    name: Deploy Grafana
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Grafana Deployment Script
        run: |
          chmod +x scripts/deploy-grafana.sh
          scripts/deploy-grafana.sh
