name: Kubernetes Deployment

on:
  workflow_run:
    workflows: ["Terraform Setup"]
    types:
      - completed

jobs:
  kubernetes:
    name: Kubernetes Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Kubernetes Deployment Script
        run: |
          chmod +x scripts/apply-kubernetes.sh
          scripts/apply-kubernetes.sh
