name: Deploy Kubernetes Resources

on:
  workflow_run:
    workflows: ["Terraform Setup"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy Kubernetes Resources
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.REGION }} 
      EKS_CLUSTER_NAME: ${{ secrets.AWS_CLUSTER_NAME}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      - name: Make script executable
        run: chmod +x scripts/apply-kubernetes.sh

      - name: Run Kubernetes Deployment Script
        run: ./scripts/apply-kubernetes.sh
