name: Deploy Monitoring

on:
  workflow_run:
    workflows: ["Kubernetes Deployment"]
    types:
      - completed

env:
  AWS_REGION: ${{ vars.REGION }}

jobs:
  monitoring:
    name: 'Deploy Monitoring'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name "socksShop-eks-hakeem" --region ${{ env.AWS_REGION }}

    - name: Deploy Prometheus
      run: |
        chmod +x scripts/deploy-prometheus.sh
        scripts/deploy-prometheus.sh

    - name: Deploy Grafana
      run: |
        chmod +x scripts/deploy-grafana.sh
        scripts/deploy-grafana.sh
