name: Deploy Prometheus

on:
  workflow_run:
    workflows: ["Kubernetes Deployment"]
    types:
      - completed

jobs:
  prometheus:
    name: Deploy Prometheus
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Prometheus Deployment Script
        run: |
          chmod +x scripts/deploy-prometheus.sh
          scripts/deploy-prometheus.sh
