name: Prometheus Deployment

on:
  workflow_run:
    workflows: ["Kubernetes Deployment"]
    types:
      - completed

jobs:
  prometheus:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.REGION }}
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ needs.terraform.outputs.cluster_name }} --region ${{ vars.REGION }}
    - name: Deploy Prometheus
      env:
        CLUSTER_NAME: ${{ needs.terraform.outputs.cluster_name }}
      run: |
        chmod +x ./scripts/deploy-prometheus.sh
        ./scripts/deploy-prometheus.sh
