name: Manual Rollback

on:
  workflow_dispatch:

jobs:
  rollback:
    name: Rollback Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Rollback Script
        run: |
          chmod +x ./scripts/rollback.sh
          ./scripts/rollback.sh
