name: Manual Rollback

on:
  workflow_dispatch:

jobs:
  rollback:
    name: Rollback Changes
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ vars.REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Rollback Script
        run: |
          chmod +x scripts/rollback.sh
          scripts/rollback.sh
