name: Terraform Setup

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Terraform Setup Script
        run: |
          chmod +x ./scripts/terraform_setup.sh
          ./scripts/terraform_setup.sh
