name: Terraform Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.REGION }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      cluster_name: ${{ steps.terraform-output.outputs.cluster_name }}
      region: ${{ steps.terraform-output.outputs.region }}
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.REGION }}
    - name: Run Terraform
      run: |
        chmod +x ./scripts/run-terraform.sh
        ./scripts/run-terraform.sh
    - name: Capture Terraform Output
      id: terraform-output
      run: |
        terraform output -raw cluster_name > cluster_name.txt
        terraform output -raw region > region.txt
        echo "cluster_name=$(cat cluster_name.txt)" >> $GITHUB_ENV
        echo "region=$(cat region.txt)" >> $GITHUB_ENV
